---
title: "Cleaning and analysis of Ilastik-generated csv files with the IlastiKlean package"
author: "Stacy Welker, Jacobo Robledo Buritica"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Cleaning and analysis of Ilastik-generated csv files with the IlastiKlean package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## Introduction

Ilastik is a free tool, developed by the Ilastik team at the [European Molecular Biological Laboratory](https://www.embl.org/sites/heidelberg/), which uses supervised machine learning to segment images and other types of visual data sets. Download files and official documentation for Ilastik can be found [at the official Ilastik website](https://www.ilastik.org/). The expert user trains a specialized classifier on a subset of their data by applying labels with a point and click interface. The rest of the data set can then be automatically segmented with the trained classifier.  


For each image which is segmented using the object classifier workflow, Ilastik will generate a .csv file in which each line represents information about a single object from the image. The information parameters are chosen by the user. For some datasets, this can be hundreds of files. This quantity of information is best managed with statistical programming tools such as R.   


In the course of using Ilastik and R scripts to quantify objects in images for various projects, I found myself repeatedly performing the same steps. To avoid this repetition and to simplify the analysis for new users of Ilastik, Jacob and I decided to make an R package to handle the .csv files. This vignette will provide instructions for the use of this package, which we called IlastiKlean. IlastiKlean was specifically made to handle confocal microscopic images of plant phloem, but it was designed to be generalizable to any .csv files generated by Ilastik.  


## Data preparation and cleaning

Begin by specifying the working directory, the drive where the .csv files are located and where all outputs from the R script will be saved. R requires that all backslashes in file names be changed to forward slashes.

```
setwd("C:/Users/username/university_working_drive/project_folder/filtered_image_data")
```
Load the necessary packages. 

```
# If you don't have devtools installed:

install.packages("devtools")

# Install the KleanLastic package:

devtools::install_github("jrobledob/IlastiKlean")

# Load the libraries

library(IlastiKlean)
library(dplyr)
library(stringr)
library(tidyr)
library(car)
library(multcomp)
```
Next, load the data.  
<br>

If you don’t have a data set but want to test the package out, IlastiKlean comes with a function that creates mock data.  The user can specify how many sample groups and how many images to generate from each sample group.  In the wor_dir argument, type the name of the drive where you want the csv files to be created, if it is different from your current working directory. If you already have data, you can skip this step and proceed to the next one.

```
mock_data <- sim_Ilastik_output(samples = 3, pictures = 3)
mock_data

```

The function `read_and_clean_csvs` in the package IlastiKlean will create a new data frame. It reads all .csv files from the specified directory, converts all the columns to characters, combines all the common columns into one big data frame, and mutates the data frame so that the file names are attached to each row.  
<br>

Keep in mind that this will load .csv files indiscriminately, so all .csv files that are exported with this script must be moved out of the drive so as not to interfere with the script in the future. In the parenthesis, place the directory where the target Ilastik output csv files are located.

```
objects_with_file_names<- read_and_clean_csvs("C:/Users/username/university_working_drive/project_folder/filtered_image_data/")
```

Correct file name formats are of paramount importance to the analysis. Each file name should be formatted so that the experimental information was stored in the same order and separated by underscores. Example: GENE1_cultivar1_treatment1_Tree3_Peel2_Image4.tif.  
<br>

The following code will provide one way to break up such a file name into columns so that the information can be used as variables in the analysis. Sometimes the microscope imaging software adds information at the beginning or end of each file name that is repetitive and unneeded. The first mutate line in this block will remove text from the beginning and the second mutate line will remove it from the end. The user must replace their unneeded information with the text in the first set of quotation marks on each line. If there is no unneeded information in the file name, this step can be skipped.

```
objects_with_file_names<- objects_with_file_names %>%
  mutate(filename = str_replace_all(filename, "dataset.ch00_", "")) %>%
  mutate(filename = str_replace_all(filename, ".csv", ""))

```

In the mock dataset, the file name will be broken into three columns. For an experimental dataset, the user will change the variable names and number of names as needed next to `names =`. The word “merge” in the too_many portion can be replaced with “debug” to help spot erroneous file names. A too_few portion can also be added to diagnose errors in the same parenthesis (function parameters). For a real dataset, erroneous names can be addressed in the script with a regex expression, but it will be less complicated for the novice user to go back into the folder, fix the file name there, and reload the .csv files.

```
objects_with_file_names<- objects_with_file_names %>% 
  separate_wider_delim(filename, delim = "_", names = c("plant", "sample", "pic_number"), too_many = "merge)

```

The summarize_callose_data() function creates a summary of information about the target objects. The function was originally created to summarize counts of callose formations in florescent plant phloem images, but it can be used to summarize information about any class of objects desired by the user. Simply replace "Callose" next to `target_class =` with the desired object. Also replace the information next to `group_vars =` with the names from the previous step.  
<br>

The function will count the total number of images per group, filtering for the target class, calculate the number and average size of detected objects per image, and merge these results with a complete reference of all images to ensure images with zero objects are properly included. Missing values are filled with zeros to maintain accurate group-level summaries. The complete summary data frame can optionally be saved as a CSV file for further analysis. 

```
summary_df <- summarize_callose_data(df = objects_with_file_names, target_class = "Callose", group_vars = c("plant", "sample", "pic_number"), output_csv = "summary_output.csv")
```

## Data Visualization and suggested statistical analysis

The visualize_and_analyze_callose() function of the IlastiKlean package is a tool for visualizing the dataframe created in the previous step. Internally, the function begins by generating a clean and customizable boxplot of target object counts grouped by plant (or any specified grouping variable), providing a clear visual comparison of their distributions. It optionally saves this plot as a high-resolution PNG file. It then displays a histogram of the callose count data to give a quick visual impression of the distribution.  

<br>
Next, the function performs a Shapiro-Wilk test to assess whether the target counts follow a normal distribution. Based on this result, it automatically selects and runs the appropriate statistical test: a Welch two-sample t-test if normality is assumed, or a non-parametric Wilcoxon rank-sum test if the data deviate from normality. This is the simplest and most common analysis for this type of data, assuming a single pairwise comparison, but further analysis can be carried out by more experienced users as needed. This straightforward approach is typically sufficient for most novice users.
```
analysis_result <- visualize_and_analyze_callose(df = summary_df, group_col = "plant", count_col = "callose_count", boxplot_filename = "count_box_plot.png")

```
